# config/packages/messenger.yaml

framework:
    messenger:
        # Supprimer ou commenter cette section si tu ne veux pas utiliser Messenger
        transports: []
        
        # Si tu veux désactiver l'utilisation de l'async ou des autres buses
        default_bus: messenger.bus.default
        buses:
            messenger.bus.default: []
        routing: []
