security:
  password_hashers:
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username   # ← on se connecte via le login

  role_hierarchy:
    ROLE_ADMIN: [ROLE_MEMBER, ROLE_RESTRICTED, ROLE_GUEST, ROLE_USER]
    ROLE_MEMBER: [ROLE_USER]
    ROLE_RESTRICTED: [ROLE_USER]
    ROLE_GUEST: [ROLE_USER]

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true
        default_target_path: app_home   # ← route d’accueil après login (adapte si besoin)
      logout:
        path: app_logout
        target: app_home

  access_control:

    - { path: ^/castellum, roles: ROLE_USER }
    - { path: ^/projets, roles: IS_AUTHENTICATED_FULLY }

    # Exemples de restrictions :
    - { path: ^/boutique/new, roles: ROLE_MEMBER }
    - { path: ^/boutique/\d+/(edit|delete), roles: ROLE_MEMBER }
    - { path: ^/admin, roles: ROLE_ADMIN }

