# config/routes.yaml

# Route manuelle pour la page d'accueil
app_home:
  path: /
  controller: App\Controller\HomeController::index

# Charger toutes les routes des contrôleurs avec attributs
controllers:
  resource: '../src/Controller/'
  type: attribute
